# Generated by Django 3.0.7 on 2020-06-25 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_page_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('url', models.URLField()),
                ('status_code', models.IntegerField()),
                ('page_content', models.TextField()),
                ('status_process', models.IntegerField()),
                ('error_msg', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('waiting', models.IntegerField()),
                ('scroll', models.IntegerField()),
            ],
        ),
    ]
