# Generated by Django 3.0.7 on 2020-06-26 12:17

from django.db import migrations, models
import django.utils.timezone
import task1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_page_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=task1.models.get_auto_generated_task_id, editable=False, unique=True)),
                ('url', models.URLField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('page_content', models.TextField(blank=True, null=True)),
                ('status_process', models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('pending', 'pending'), ('error', 'error')], default='processing', max_length=50)),
                ('error_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('waiting', models.IntegerField(blank=True, null=True)),
                ('scroll', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
